# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config
[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "shanghai"
  fs_permissions = [{ access = "read-write", path = "./results" }]
  gas_limit = 9223372036854775807
  optimizer = true
  optimizer_runs = 1000
  out = "out"
  solc = "0.8.29"

[profile.flow]
  src = "src/flow"
  test = "src/flow"

[profile.lockup]
  src = "src/lockup"
  test = "src/lockup"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[lint]
  lint_on_build = false

[rpc_endpoints]
  mainnet = "https://direct.routeme.sh/rpc/1/${ROUTEMESH_API_KEY}"
